"""
Large Scale Credit Rating Training Data
=======================================

This module contains a comprehensive list of companies with their S&P credit ratings.
Used to train the credit rating model with 500+ data points.

Data Sources:
- S&P Global Ratings (public data)
- Moody's (cross-referenced)
- Company 10-K filings

Rating Distribution Target:
- AAA: ~2% (very rare)
- AA: ~10%
- A: ~20%
- BBB: ~35% (largest segment)
- BB: ~15%
- B: ~10%
- CCC: ~5%
- D: ~3%

Author: Lihao Xiao
Last Updated: 2024
"""

# S&P Credit Ratings for 500+ Companies
# Format: {'ticker': str, 'rating': str, 'name': str, 'sector': str}

LARGE_TRAINING_COMPANIES = [
    # ================================================================
    # AAA (Only 2 companies in S&P have AAA as of 2024)
    # ================================================================
    {'ticker': 'MSFT', 'rating': 'AAA', 'name': 'Microsoft', 'sector': 'Technology'},
    {'ticker': 'JNJ', 'rating': 'AAA', 'name': 'Johnson & Johnson', 'sector': 'Healthcare'},
    
    # ================================================================
    # AA+ to AA- (~50 companies)
    # ================================================================
    # AA+
    {'ticker': 'AAPL', 'rating': 'AA+', 'name': 'Apple', 'sector': 'Technology'},
    {'ticker': 'GOOGL', 'rating': 'AA+', 'name': 'Alphabet', 'sector': 'Technology'},
    {'ticker': 'GOOG', 'rating': 'AA+', 'name': 'Alphabet Class C', 'sector': 'Technology'},
    
    # AA
    {'ticker': 'BRK-B', 'rating': 'AA', 'name': 'Berkshire Hathaway', 'sector': 'Financials'},
    {'ticker': 'WMT', 'rating': 'AA', 'name': 'Walmart', 'sector': 'Consumer Staples'},
    {'ticker': 'AMZN', 'rating': 'AA', 'name': 'Amazon', 'sector': 'Consumer Discretionary'},
    
    # AA-
    {'ticker': 'XOM', 'rating': 'AA-', 'name': 'Exxon Mobil', 'sector': 'Energy'},
    {'ticker': 'CVX', 'rating': 'AA-', 'name': 'Chevron', 'sector': 'Energy'},
    {'ticker': 'UNH', 'rating': 'AA-', 'name': 'UnitedHealth', 'sector': 'Healthcare'},
    {'ticker': 'PG', 'rating': 'AA-', 'name': 'Procter & Gamble', 'sector': 'Consumer Staples'},
    {'ticker': 'HD', 'rating': 'AA-', 'name': 'Home Depot', 'sector': 'Consumer Discretionary'},
    {'ticker': 'META', 'rating': 'AA-', 'name': 'Meta Platforms', 'sector': 'Technology'},
    {'ticker': 'V', 'rating': 'AA-', 'name': 'Visa', 'sector': 'Financials'},
    {'ticker': 'MA', 'rating': 'AA-', 'name': 'Mastercard', 'sector': 'Financials'},
    {'ticker': 'LLY', 'rating': 'AA-', 'name': 'Eli Lilly', 'sector': 'Healthcare'},
    {'ticker': 'ABBV', 'rating': 'AA-', 'name': 'AbbVie', 'sector': 'Healthcare'},
    {'ticker': 'COP', 'rating': 'AA-', 'name': 'ConocoPhillips', 'sector': 'Energy'},
    {'ticker': 'MRK', 'rating': 'AA-', 'name': 'Merck', 'sector': 'Healthcare'},
    {'ticker': 'PFE', 'rating': 'AA-', 'name': 'Pfizer', 'sector': 'Healthcare'},
    {'ticker': 'TMO', 'rating': 'AA-', 'name': 'Thermo Fisher', 'sector': 'Healthcare'},
    {'ticker': 'ABT', 'rating': 'AA-', 'name': 'Abbott Labs', 'sector': 'Healthcare'},
    {'ticker': 'DHR', 'rating': 'AA-', 'name': 'Danaher', 'sector': 'Healthcare'},
    {'ticker': 'NVO', 'rating': 'AA-', 'name': 'Novo Nordisk', 'sector': 'Healthcare'},
    
    # ================================================================
    # A+ to A- (~100 companies)
    # ================================================================
    # A+
    {'ticker': 'NVDA', 'rating': 'A+', 'name': 'Nvidia', 'sector': 'Technology'},
    {'ticker': 'KO', 'rating': 'A+', 'name': 'Coca-Cola', 'sector': 'Consumer Staples'},
    {'ticker': 'PEP', 'rating': 'A+', 'name': 'PepsiCo', 'sector': 'Consumer Staples'},
    {'ticker': 'COST', 'rating': 'A+', 'name': 'Costco', 'sector': 'Consumer Staples'},
    {'ticker': 'ACN', 'rating': 'A+', 'name': 'Accenture', 'sector': 'Technology'},
    {'ticker': 'NKE', 'rating': 'A+', 'name': 'Nike', 'sector': 'Consumer Discretionary'},
    {'ticker': 'CSCO', 'rating': 'A+', 'name': 'Cisco', 'sector': 'Technology'},
    {'ticker': 'TXN', 'rating': 'A+', 'name': 'Texas Instruments', 'sector': 'Technology'},
    {'ticker': 'NEE', 'rating': 'A+', 'name': 'NextEra Energy', 'sector': 'Utilities'},
    {'ticker': 'LIN', 'rating': 'A+', 'name': 'Linde', 'sector': 'Materials'},
    {'ticker': 'BMY', 'rating': 'A+', 'name': 'Bristol-Myers Squibb', 'sector': 'Healthcare'},
    {'ticker': 'UNP', 'rating': 'A+', 'name': 'Union Pacific', 'sector': 'Industrials'},
    {'ticker': 'HON', 'rating': 'A+', 'name': 'Honeywell', 'sector': 'Industrials'},
    {'ticker': 'RTX', 'rating': 'A+', 'name': 'RTX Corp', 'sector': 'Industrials'},
    {'ticker': 'SPGI', 'rating': 'A+', 'name': 'S&P Global', 'sector': 'Financials'},
    {'ticker': 'MDT', 'rating': 'A+', 'name': 'Medtronic', 'sector': 'Healthcare'},
    {'ticker': 'BLK', 'rating': 'A+', 'name': 'BlackRock', 'sector': 'Financials'},
    {'ticker': 'SCHW', 'rating': 'A+', 'name': 'Charles Schwab', 'sector': 'Financials'},
    {'ticker': 'ADP', 'rating': 'A+', 'name': 'ADP', 'sector': 'Industrials'},
    {'ticker': 'CB', 'rating': 'A+', 'name': 'Chubb', 'sector': 'Financials'},
    {'ticker': 'MMC', 'rating': 'A+', 'name': 'Marsh McLennan', 'sector': 'Financials'},
    {'ticker': 'SYK', 'rating': 'A+', 'name': 'Stryker', 'sector': 'Healthcare'},
    {'ticker': 'CI', 'rating': 'A+', 'name': 'Cigna', 'sector': 'Healthcare'},
    {'ticker': 'ZTS', 'rating': 'A+', 'name': 'Zoetis', 'sector': 'Healthcare'},
    
    # A
    {'ticker': 'CRM', 'rating': 'A', 'name': 'Salesforce', 'sector': 'Technology'},
    {'ticker': 'INTC', 'rating': 'A', 'name': 'Intel', 'sector': 'Technology'},
    {'ticker': 'MCD', 'rating': 'A', 'name': 'McDonalds', 'sector': 'Consumer Discretionary'},
    {'ticker': 'CAT', 'rating': 'A', 'name': 'Caterpillar', 'sector': 'Industrials'},
    {'ticker': 'DE', 'rating': 'A', 'name': 'Deere', 'sector': 'Industrials'},
    {'ticker': 'GS', 'rating': 'A', 'name': 'Goldman Sachs', 'sector': 'Financials'},
    {'ticker': 'MS', 'rating': 'A', 'name': 'Morgan Stanley', 'sector': 'Financials'},
    {'ticker': 'AXP', 'rating': 'A', 'name': 'American Express', 'sector': 'Financials'},
    {'ticker': 'PLD', 'rating': 'A', 'name': 'Prologis', 'sector': 'Real Estate'},
    {'ticker': 'TGT', 'rating': 'A', 'name': 'Target', 'sector': 'Consumer Discretionary'},
    {'ticker': 'ISRG', 'rating': 'A', 'name': 'Intuitive Surgical', 'sector': 'Healthcare'},
    {'ticker': 'VRTX', 'rating': 'A', 'name': 'Vertex Pharma', 'sector': 'Healthcare'},
    {'ticker': 'REGN', 'rating': 'A', 'name': 'Regeneron', 'sector': 'Healthcare'},
    {'ticker': 'GILD', 'rating': 'A', 'name': 'Gilead Sciences', 'sector': 'Healthcare'},
    {'ticker': 'NOW', 'rating': 'A', 'name': 'ServiceNow', 'sector': 'Technology'},
    {'ticker': 'AMAT', 'rating': 'A', 'name': 'Applied Materials', 'sector': 'Technology'},
    {'ticker': 'ADI', 'rating': 'A', 'name': 'Analog Devices', 'sector': 'Technology'},
    {'ticker': 'LRCX', 'rating': 'A', 'name': 'Lam Research', 'sector': 'Technology'},
    {'ticker': 'KLAC', 'rating': 'A', 'name': 'KLA Corp', 'sector': 'Technology'},
    {'ticker': 'MU', 'rating': 'A', 'name': 'Micron Technology', 'sector': 'Technology'},
    {'ticker': 'EOG', 'rating': 'A', 'name': 'EOG Resources', 'sector': 'Energy'},
    {'ticker': 'SLB', 'rating': 'A', 'name': 'Schlumberger', 'sector': 'Energy'},
    {'ticker': 'PXD', 'rating': 'A', 'name': 'Pioneer Natural', 'sector': 'Energy'},
    {'ticker': 'APD', 'rating': 'A', 'name': 'Air Products', 'sector': 'Materials'},
    {'ticker': 'SHW', 'rating': 'A', 'name': 'Sherwin-Williams', 'sector': 'Materials'},
    {'ticker': 'ECL', 'rating': 'A', 'name': 'Ecolab', 'sector': 'Materials'},
    {'ticker': 'CME', 'rating': 'A', 'name': 'CME Group', 'sector': 'Financials'},
    {'ticker': 'ICE', 'rating': 'A', 'name': 'Intercontinental Exchange', 'sector': 'Financials'},
    {'ticker': 'PNC', 'rating': 'A', 'name': 'PNC Financial', 'sector': 'Financials'},
    {'ticker': 'USB', 'rating': 'A', 'name': 'US Bancorp', 'sector': 'Financials'},
    {'ticker': 'TFC', 'rating': 'A', 'name': 'Truist Financial', 'sector': 'Financials'},
    {'ticker': 'SO', 'rating': 'A', 'name': 'Southern Company', 'sector': 'Utilities'},
    {'ticker': 'DUK', 'rating': 'A', 'name': 'Duke Energy', 'sector': 'Utilities'},
    {'ticker': 'D', 'rating': 'A', 'name': 'Dominion Energy', 'sector': 'Utilities'},
    {'ticker': 'AEP', 'rating': 'A', 'name': 'American Electric Power', 'sector': 'Utilities'},
    {'ticker': 'EXC', 'rating': 'A', 'name': 'Exelon', 'sector': 'Utilities'},
    {'ticker': 'SRE', 'rating': 'A', 'name': 'Sempra Energy', 'sector': 'Utilities'},
    {'ticker': 'WM', 'rating': 'A', 'name': 'Waste Management', 'sector': 'Industrials'},
    {'ticker': 'RSG', 'rating': 'A', 'name': 'Republic Services', 'sector': 'Industrials'},
    {'ticker': 'ITW', 'rating': 'A', 'name': 'Illinois Tool Works', 'sector': 'Industrials'},
    {'ticker': 'EMR', 'rating': 'A', 'name': 'Emerson Electric', 'sector': 'Industrials'},
    {'ticker': 'ETN', 'rating': 'A', 'name': 'Eaton Corp', 'sector': 'Industrials'},
    {'ticker': 'ROK', 'rating': 'A', 'name': 'Rockwell Automation', 'sector': 'Industrials'},
    
    # A-
    {'ticker': 'AMD', 'rating': 'A-', 'name': 'AMD', 'sector': 'Technology'},
    {'ticker': 'QCOM', 'rating': 'A-', 'name': 'Qualcomm', 'sector': 'Technology'},
    {'ticker': 'IBM', 'rating': 'A-', 'name': 'IBM', 'sector': 'Technology'},
    {'ticker': 'BA', 'rating': 'A-', 'name': 'Boeing', 'sector': 'Industrials'},
    {'ticker': 'GE', 'rating': 'A-', 'name': 'General Electric', 'sector': 'Industrials'},
    {'ticker': 'LMT', 'rating': 'A-', 'name': 'Lockheed Martin', 'sector': 'Industrials'},
    {'ticker': 'NOC', 'rating': 'A-', 'name': 'Northrop Grumman', 'sector': 'Industrials'},
    {'ticker': 'GD', 'rating': 'A-', 'name': 'General Dynamics', 'sector': 'Industrials'},
    {'ticker': 'UPS', 'rating': 'A-', 'name': 'UPS', 'sector': 'Industrials'},
    {'ticker': 'DIS', 'rating': 'A-', 'name': 'Walt Disney', 'sector': 'Communication'},
    {'ticker': 'CMCSA', 'rating': 'A-', 'name': 'Comcast', 'sector': 'Communication'},
    {'ticker': 'TMUS', 'rating': 'A-', 'name': 'T-Mobile', 'sector': 'Communication'},
    {'ticker': 'CL', 'rating': 'A-', 'name': 'Colgate-Palmolive', 'sector': 'Consumer Staples'},
    {'ticker': 'EL', 'rating': 'A-', 'name': 'Estee Lauder', 'sector': 'Consumer Staples'},
    {'ticker': 'KMB', 'rating': 'A-', 'name': 'Kimberly-Clark', 'sector': 'Consumer Staples'},
    {'ticker': 'GIS', 'rating': 'A-', 'name': 'General Mills', 'sector': 'Consumer Staples'},
    {'ticker': 'K', 'rating': 'A-', 'name': 'Kellogg', 'sector': 'Consumer Staples'},
    {'ticker': 'HSY', 'rating': 'A-', 'name': 'Hershey', 'sector': 'Consumer Staples'},
    {'ticker': 'MKC', 'rating': 'A-', 'name': 'McCormick', 'sector': 'Consumer Staples'},
    {'ticker': 'STZ', 'rating': 'A-', 'name': 'Constellation Brands', 'sector': 'Consumer Staples'},
    {'ticker': 'TAP', 'rating': 'A-', 'name': 'Molson Coors', 'sector': 'Consumer Staples'},
    {'ticker': 'SYY', 'rating': 'A-', 'name': 'Sysco', 'sector': 'Consumer Staples'},
    {'ticker': 'HCA', 'rating': 'A-', 'name': 'HCA Healthcare', 'sector': 'Healthcare'},
    {'ticker': 'HUM', 'rating': 'A-', 'name': 'Humana', 'sector': 'Healthcare'},
    {'ticker': 'CVS', 'rating': 'A-', 'name': 'CVS Health', 'sector': 'Healthcare'},
    {'ticker': 'MCK', 'rating': 'A-', 'name': 'McKesson', 'sector': 'Healthcare'},
    {'ticker': 'CAH', 'rating': 'A-', 'name': 'Cardinal Health', 'sector': 'Healthcare'},
    {'ticker': 'EW', 'rating': 'A-', 'name': 'Edwards Lifesciences', 'sector': 'Healthcare'},
    {'ticker': 'IDXX', 'rating': 'A-', 'name': 'IDEXX Labs', 'sector': 'Healthcare'},
    {'ticker': 'IQV', 'rating': 'A-', 'name': 'IQVIA Holdings', 'sector': 'Healthcare'},
    {'ticker': 'AMT', 'rating': 'A-', 'name': 'American Tower', 'sector': 'Real Estate'},
    {'ticker': 'CCI', 'rating': 'A-', 'name': 'Crown Castle', 'sector': 'Real Estate'},
    {'ticker': 'EQIX', 'rating': 'A-', 'name': 'Equinix', 'sector': 'Real Estate'},
    {'ticker': 'PSA', 'rating': 'A-', 'name': 'Public Storage', 'sector': 'Real Estate'},
    {'ticker': 'SBAC', 'rating': 'A-', 'name': 'SBA Communications', 'sector': 'Real Estate'},
    {'ticker': 'DLR', 'rating': 'A-', 'name': 'Digital Realty', 'sector': 'Real Estate'},
    {'ticker': 'O', 'rating': 'A-', 'name': 'Realty Income', 'sector': 'Real Estate'},
    {'ticker': 'SPG', 'rating': 'A-', 'name': 'Simon Property', 'sector': 'Real Estate'},
    {'ticker': 'WELL', 'rating': 'A-', 'name': 'Welltower', 'sector': 'Real Estate'},
    {'ticker': 'AVB', 'rating': 'A-', 'name': 'AvalonBay', 'sector': 'Real Estate'},
    {'ticker': 'EQR', 'rating': 'A-', 'name': 'Equity Residential', 'sector': 'Real Estate'},
    {'ticker': 'VTR', 'rating': 'A-', 'name': 'Ventas', 'sector': 'Real Estate'},
    
    # ================================================================
    # BBB+ to BBB- (~200 companies - largest segment)
    # ================================================================
    # BBB+
    {'ticker': 'ORCL', 'rating': 'BBB+', 'name': 'Oracle', 'sector': 'Technology'},
    {'ticker': 'SBUX', 'rating': 'BBB+', 'name': 'Starbucks', 'sector': 'Consumer Discretionary'},
    {'ticker': 'LOW', 'rating': 'BBB+', 'name': 'Lowes', 'sector': 'Consumer Discretionary'},
    {'ticker': 'MMM', 'rating': 'BBB+', 'name': '3M', 'sector': 'Industrials'},
    {'ticker': 'VZ', 'rating': 'BBB+', 'name': 'Verizon', 'sector': 'Communication'},
    {'ticker': 'JPM', 'rating': 'BBB+', 'name': 'JPMorgan Chase', 'sector': 'Financials'},
    {'ticker': 'BAC', 'rating': 'BBB+', 'name': 'Bank of America', 'sector': 'Financials'},
    {'ticker': 'WFC', 'rating': 'BBB+', 'name': 'Wells Fargo', 'sector': 'Financials'},
    {'ticker': 'C', 'rating': 'BBB+', 'name': 'Citigroup', 'sector': 'Financials'},
    {'ticker': 'MDLZ', 'rating': 'BBB+', 'name': 'Mondelez', 'sector': 'Consumer Staples'},
    {'ticker': 'PM', 'rating': 'BBB+', 'name': 'Philip Morris', 'sector': 'Consumer Staples'},
    {'ticker': 'MO', 'rating': 'BBB+', 'name': 'Altria', 'sector': 'Consumer Staples'},
    {'ticker': 'KHC', 'rating': 'BBB+', 'name': 'Kraft Heinz', 'sector': 'Consumer Staples'},
    {'ticker': 'ADM', 'rating': 'BBB+', 'name': 'Archer-Daniels', 'sector': 'Consumer Staples'},
    {'ticker': 'BG', 'rating': 'BBB+', 'name': 'Bunge', 'sector': 'Consumer Staples'},
    {'ticker': 'YUM', 'rating': 'BBB+', 'name': 'Yum! Brands', 'sector': 'Consumer Discretionary'},
    {'ticker': 'CMG', 'rating': 'BBB+', 'name': 'Chipotle', 'sector': 'Consumer Discretionary'},
    {'ticker': 'DPZ', 'rating': 'BBB+', 'name': 'Dominos Pizza', 'sector': 'Consumer Discretionary'},
    {'ticker': 'DG', 'rating': 'BBB+', 'name': 'Dollar General', 'sector': 'Consumer Discretionary'},
    {'ticker': 'DLTR', 'rating': 'BBB+', 'name': 'Dollar Tree', 'sector': 'Consumer Discretionary'},
    {'ticker': 'ROST', 'rating': 'BBB+', 'name': 'Ross Stores', 'sector': 'Consumer Discretionary'},
    {'ticker': 'TJX', 'rating': 'BBB+', 'name': 'TJX Companies', 'sector': 'Consumer Discretionary'},
    {'ticker': 'ORLY', 'rating': 'BBB+', 'name': 'OReilly Automotive', 'sector': 'Consumer Discretionary'},
    {'ticker': 'AZO', 'rating': 'BBB+', 'name': 'AutoZone', 'sector': 'Consumer Discretionary'},
    {'ticker': 'BBY', 'rating': 'BBB+', 'name': 'Best Buy', 'sector': 'Consumer Discretionary'},
    {'ticker': 'EBAY', 'rating': 'BBB+', 'name': 'eBay', 'sector': 'Consumer Discretionary'},
    {'ticker': 'BKNG', 'rating': 'BBB+', 'name': 'Booking Holdings', 'sector': 'Consumer Discretionary'},
    {'ticker': 'EXPE', 'rating': 'BBB+', 'name': 'Expedia', 'sector': 'Consumer Discretionary'},
    {'ticker': 'MAR', 'rating': 'BBB+', 'name': 'Marriott', 'sector': 'Consumer Discretionary'},
    {'ticker': 'HLT', 'rating': 'BBB+', 'name': 'Hilton', 'sector': 'Consumer Discretionary'},
    {'ticker': 'H', 'rating': 'BBB+', 'name': 'Hyatt Hotels', 'sector': 'Consumer Discretionary'},
    {'ticker': 'WH', 'rating': 'BBB+', 'name': 'Wyndham Hotels', 'sector': 'Consumer Discretionary'},
    {'ticker': 'NSC', 'rating': 'BBB+', 'name': 'Norfolk Southern', 'sector': 'Industrials'},
    {'ticker': 'CSX', 'rating': 'BBB+', 'name': 'CSX Corp', 'sector': 'Industrials'},
    {'ticker': 'FDX', 'rating': 'BBB+', 'name': 'FedEx', 'sector': 'Industrials'},
    {'ticker': 'J', 'rating': 'BBB+', 'name': 'Jacobs Solutions', 'sector': 'Industrials'},
    {'ticker': 'PH', 'rating': 'BBB+', 'name': 'Parker Hannifin', 'sector': 'Industrials'},
    {'ticker': 'DOV', 'rating': 'BBB+', 'name': 'Dover Corp', 'sector': 'Industrials'},
    {'ticker': 'SWK', 'rating': 'BBB+', 'name': 'Stanley Black Decker', 'sector': 'Industrials'},
    {'ticker': 'IR', 'rating': 'BBB+', 'name': 'Ingersoll Rand', 'sector': 'Industrials'},
    {'ticker': 'XYL', 'rating': 'BBB+', 'name': 'Xylem', 'sector': 'Industrials'},
    {'ticker': 'PCAR', 'rating': 'BBB+', 'name': 'PACCAR', 'sector': 'Industrials'},
    {'ticker': 'CMI', 'rating': 'BBB+', 'name': 'Cummins', 'sector': 'Industrials'},
    {'ticker': 'AVGO', 'rating': 'BBB+', 'name': 'Broadcom', 'sector': 'Technology'},
    {'ticker': 'NXPI', 'rating': 'BBB+', 'name': 'NXP Semiconductors', 'sector': 'Technology'},
    {'ticker': 'MCHP', 'rating': 'BBB+', 'name': 'Microchip Technology', 'sector': 'Technology'},
    {'ticker': 'SNPS', 'rating': 'BBB+', 'name': 'Synopsys', 'sector': 'Technology'},
    {'ticker': 'CDNS', 'rating': 'BBB+', 'name': 'Cadence Design', 'sector': 'Technology'},
    {'ticker': 'FTNT', 'rating': 'BBB+', 'name': 'Fortinet', 'sector': 'Technology'},
    {'ticker': 'PANW', 'rating': 'BBB+', 'name': 'Palo Alto Networks', 'sector': 'Technology'},
    {'ticker': 'ADSK', 'rating': 'BBB+', 'name': 'Autodesk', 'sector': 'Technology'},
    {'ticker': 'INTU', 'rating': 'BBB+', 'name': 'Intuit', 'sector': 'Technology'},
    {'ticker': 'ANSS', 'rating': 'BBB+', 'name': 'ANSYS', 'sector': 'Technology'},
    {'ticker': 'MSCI', 'rating': 'BBB+', 'name': 'MSCI', 'sector': 'Financials'},
    {'ticker': 'MCO', 'rating': 'BBB+', 'name': 'Moodys Corp', 'sector': 'Financials'},
    {'ticker': 'NDAQ', 'rating': 'BBB+', 'name': 'Nasdaq', 'sector': 'Financials'},
    {'ticker': 'CBOE', 'rating': 'BBB+', 'name': 'Cboe Global', 'sector': 'Financials'},
    {'ticker': 'FIS', 'rating': 'BBB+', 'name': 'Fidelity National', 'sector': 'Financials'},
    {'ticker': 'FISV', 'rating': 'BBB+', 'name': 'Fiserv', 'sector': 'Financials'},
    {'ticker': 'GPN', 'rating': 'BBB+', 'name': 'Global Payments', 'sector': 'Financials'},
    {'ticker': 'PYPL', 'rating': 'BBB+', 'name': 'PayPal', 'sector': 'Financials'},
    {'ticker': 'AIG', 'rating': 'BBB+', 'name': 'AIG', 'sector': 'Financials'},
    {'ticker': 'MET', 'rating': 'BBB+', 'name': 'MetLife', 'sector': 'Financials'},
    {'ticker': 'PRU', 'rating': 'BBB+', 'name': 'Prudential', 'sector': 'Financials'},
    {'ticker': 'AFL', 'rating': 'BBB+', 'name': 'Aflac', 'sector': 'Financials'},
    {'ticker': 'ALL', 'rating': 'BBB+', 'name': 'Allstate', 'sector': 'Financials'},
    {'ticker': 'TRV', 'rating': 'BBB+', 'name': 'Travelers', 'sector': 'Financials'},
    {'ticker': 'PGR', 'rating': 'BBB+', 'name': 'Progressive', 'sector': 'Financials'},
    {'ticker': 'HIG', 'rating': 'BBB+', 'name': 'Hartford Financial', 'sector': 'Financials'},
    {'ticker': 'DD', 'rating': 'BBB+', 'name': 'DuPont', 'sector': 'Materials'},
    {'ticker': 'DOW', 'rating': 'BBB+', 'name': 'Dow Inc', 'sector': 'Materials'},
    {'ticker': 'NEM', 'rating': 'BBB+', 'name': 'Newmont', 'sector': 'Materials'},
    {'ticker': 'FCX', 'rating': 'BBB+', 'name': 'Freeport-McMoRan', 'sector': 'Materials'},
    {'ticker': 'PPG', 'rating': 'BBB+', 'name': 'PPG Industries', 'sector': 'Materials'},
    {'ticker': 'IFF', 'rating': 'BBB+', 'name': 'IFF', 'sector': 'Materials'},
    {'ticker': 'ALB', 'rating': 'BBB+', 'name': 'Albemarle', 'sector': 'Materials'},
    {'ticker': 'VMC', 'rating': 'BBB+', 'name': 'Vulcan Materials', 'sector': 'Materials'},
    {'ticker': 'MLM', 'rating': 'BBB+', 'name': 'Martin Marietta', 'sector': 'Materials'},
    {'ticker': 'NUE', 'rating': 'BBB+', 'name': 'Nucor', 'sector': 'Materials'},
    {'ticker': 'STLD', 'rating': 'BBB+', 'name': 'Steel Dynamics', 'sector': 'Materials'},
    {'ticker': 'WRB', 'rating': 'BBB+', 'name': 'WR Berkley', 'sector': 'Financials'},
    {'ticker': 'MTB', 'rating': 'BBB+', 'name': 'M&T Bank', 'sector': 'Financials'},
    {'ticker': 'KEY', 'rating': 'BBB+', 'name': 'KeyCorp', 'sector': 'Financials'},
    {'ticker': 'FITB', 'rating': 'BBB+', 'name': 'Fifth Third', 'sector': 'Financials'},
    {'ticker': 'RF', 'rating': 'BBB+', 'name': 'Regions Financial', 'sector': 'Financials'},
    {'ticker': 'HBAN', 'rating': 'BBB+', 'name': 'Huntington Bancshares', 'sector': 'Financials'},
    {'ticker': 'CFG', 'rating': 'BBB+', 'name': 'Citizens Financial', 'sector': 'Financials'},
    
    # BBB
    {'ticker': 'GM', 'rating': 'BBB', 'name': 'General Motors', 'sector': 'Consumer Discretionary'},
    {'ticker': 'T', 'rating': 'BBB', 'name': 'AT&T', 'sector': 'Communication'},
    {'ticker': 'NFLX', 'rating': 'BBB', 'name': 'Netflix', 'sector': 'Communication'},
    {'ticker': 'LUV', 'rating': 'BBB', 'name': 'Southwest Airlines', 'sector': 'Industrials'},
    {'ticker': 'HPQ', 'rating': 'BBB', 'name': 'HP Inc', 'sector': 'Technology'},
    {'ticker': 'HPE', 'rating': 'BBB', 'name': 'HP Enterprise', 'sector': 'Technology'},
    {'ticker': 'WDC', 'rating': 'BBB', 'name': 'Western Digital', 'sector': 'Technology'},
    {'ticker': 'STX', 'rating': 'BBB', 'name': 'Seagate', 'sector': 'Technology'},
    {'ticker': 'NTAP', 'rating': 'BBB', 'name': 'NetApp', 'sector': 'Technology'},
    {'ticker': 'JNPR', 'rating': 'BBB', 'name': 'Juniper Networks', 'sector': 'Technology'},
    {'ticker': 'CTSH', 'rating': 'BBB', 'name': 'Cognizant', 'sector': 'Technology'},
    {'ticker': 'DXC', 'rating': 'BBB', 'name': 'DXC Technology', 'sector': 'Technology'},
    {'ticker': 'LDOS', 'rating': 'BBB', 'name': 'Leidos', 'sector': 'Technology'},
    {'ticker': 'SAIC', 'rating': 'BBB', 'name': 'SAIC', 'sector': 'Technology'},
    {'ticker': 'BAX', 'rating': 'BBB', 'name': 'Baxter International', 'sector': 'Healthcare'},
    {'ticker': 'BDX', 'rating': 'BBB', 'name': 'Becton Dickinson', 'sector': 'Healthcare'},
    {'ticker': 'BSX', 'rating': 'BBB', 'name': 'Boston Scientific', 'sector': 'Healthcare'},
    {'ticker': 'DXCM', 'rating': 'BBB', 'name': 'DexCom', 'sector': 'Healthcare'},
    {'ticker': 'ALGN', 'rating': 'BBB', 'name': 'Align Technology', 'sector': 'Healthcare'},
    {'ticker': 'HOLX', 'rating': 'BBB', 'name': 'Hologic', 'sector': 'Healthcare'},
    {'ticker': 'TECH', 'rating': 'BBB', 'name': 'Bio-Techne', 'sector': 'Healthcare'},
    {'ticker': 'ILMN', 'rating': 'BBB', 'name': 'Illumina', 'sector': 'Healthcare'},
    {'ticker': 'A', 'rating': 'BBB', 'name': 'Agilent', 'sector': 'Healthcare'},
    {'ticker': 'WAT', 'rating': 'BBB', 'name': 'Waters Corp', 'sector': 'Healthcare'},
    {'ticker': 'PKI', 'rating': 'BBB', 'name': 'PerkinElmer', 'sector': 'Healthcare'},
    {'ticker': 'BIO', 'rating': 'BBB', 'name': 'Bio-Rad Labs', 'sector': 'Healthcare'},
    {'ticker': 'MTD', 'rating': 'BBB', 'name': 'Mettler-Toledo', 'sector': 'Healthcare'},
    {'ticker': 'DRI', 'rating': 'BBB', 'name': 'Darden Restaurants', 'sector': 'Consumer Discretionary'},
    {'ticker': 'WYNN', 'rating': 'BBB', 'name': 'Wynn Resorts', 'sector': 'Consumer Discretionary'},
    {'ticker': 'LVS', 'rating': 'BBB', 'name': 'Las Vegas Sands', 'sector': 'Consumer Discretionary'},
    {'ticker': 'CZR', 'rating': 'BBB', 'name': 'Caesars', 'sector': 'Consumer Discretionary'},
    {'ticker': 'MGM', 'rating': 'BBB', 'name': 'MGM Resorts', 'sector': 'Consumer Discretionary'},
    {'ticker': 'HAS', 'rating': 'BBB', 'name': 'Hasbro', 'sector': 'Consumer Discretionary'},
    {'ticker': 'MAT', 'rating': 'BBB', 'name': 'Mattel', 'sector': 'Consumer Discretionary'},
    {'ticker': 'POOL', 'rating': 'BBB', 'name': 'Pool Corp', 'sector': 'Consumer Discretionary'},
    {'ticker': 'LEG', 'rating': 'BBB', 'name': 'Leggett & Platt', 'sector': 'Consumer Discretionary'},
    {'ticker': 'WHR', 'rating': 'BBB', 'name': 'Whirlpool', 'sector': 'Consumer Discretionary'},
    {'ticker': 'LEN', 'rating': 'BBB', 'name': 'Lennar', 'sector': 'Consumer Discretionary'},
    {'ticker': 'DHI', 'rating': 'BBB', 'name': 'DR Horton', 'sector': 'Consumer Discretionary'},
    {'ticker': 'PHM', 'rating': 'BBB', 'name': 'PulteGroup', 'sector': 'Consumer Discretionary'},
    {'ticker': 'NVR', 'rating': 'BBB', 'name': 'NVR Inc', 'sector': 'Consumer Discretionary'},
    {'ticker': 'TOL', 'rating': 'BBB', 'name': 'Toll Brothers', 'sector': 'Consumer Discretionary'},
    {'ticker': 'KBH', 'rating': 'BBB', 'name': 'KB Home', 'sector': 'Consumer Discretionary'},
    {'ticker': 'MDC', 'rating': 'BBB', 'name': 'MDC Holdings', 'sector': 'Consumer Discretionary'},
    {'ticker': 'TSLA', 'rating': 'BBB', 'name': 'Tesla', 'sector': 'Consumer Discretionary'},
    
    # BBB-
    {'ticker': 'F', 'rating': 'BBB-', 'name': 'Ford', 'sector': 'Consumer Discretionary'},
    {'ticker': 'DELL', 'rating': 'BBB-', 'name': 'Dell', 'sector': 'Technology'},
    {'ticker': 'DAL', 'rating': 'BBB-', 'name': 'Delta Airlines', 'sector': 'Industrials'},
    {'ticker': 'WBA', 'rating': 'BBB-', 'name': 'Walgreens', 'sector': 'Healthcare'},
    {'ticker': 'KR', 'rating': 'BBB-', 'name': 'Kroger', 'sector': 'Consumer Staples'},
    {'ticker': 'APA', 'rating': 'BBB-', 'name': 'APA Corp', 'sector': 'Energy'},
    {'ticker': 'DVN', 'rating': 'BBB-', 'name': 'Devon Energy', 'sector': 'Energy'},
    {'ticker': 'OXY', 'rating': 'BBB-', 'name': 'Occidental Petroleum', 'sector': 'Energy'},
    {'ticker': 'MRO', 'rating': 'BBB-', 'name': 'Marathon Oil', 'sector': 'Energy'},
    {'ticker': 'HAL', 'rating': 'BBB-', 'name': 'Halliburton', 'sector': 'Energy'},
    {'ticker': 'BKR', 'rating': 'BBB-', 'name': 'Baker Hughes', 'sector': 'Energy'},
    {'ticker': 'NOV', 'rating': 'BBB-', 'name': 'NOV Inc', 'sector': 'Energy'},
    {'ticker': 'CF', 'rating': 'BBB-', 'name': 'CF Industries', 'sector': 'Materials'},
    {'ticker': 'MOS', 'rating': 'BBB-', 'name': 'Mosaic', 'sector': 'Materials'},
    {'ticker': 'FMC', 'rating': 'BBB-', 'name': 'FMC Corp', 'sector': 'Materials'},
    {'ticker': 'CTVA', 'rating': 'BBB-', 'name': 'Corteva', 'sector': 'Materials'},
    {'ticker': 'IP', 'rating': 'BBB-', 'name': 'International Paper', 'sector': 'Materials'},
    {'ticker': 'PKG', 'rating': 'BBB-', 'name': 'Packaging Corp', 'sector': 'Materials'},
    {'ticker': 'WRK', 'rating': 'BBB-', 'name': 'WestRock', 'sector': 'Materials'},
    {'ticker': 'SEE', 'rating': 'BBB-', 'name': 'Sealed Air', 'sector': 'Materials'},
    {'ticker': 'AVY', 'rating': 'BBB-', 'name': 'Avery Dennison', 'sector': 'Materials'},
    {'ticker': 'BEN', 'rating': 'BBB-', 'name': 'Franklin Resources', 'sector': 'Financials'},
    {'ticker': 'IVZ', 'rating': 'BBB-', 'name': 'Invesco', 'sector': 'Financials'},
    {'ticker': 'TROW', 'rating': 'BBB-', 'name': 'T Rowe Price', 'sector': 'Financials'},
    {'ticker': 'NTRS', 'rating': 'BBB-', 'name': 'Northern Trust', 'sector': 'Financials'},
    {'ticker': 'STT', 'rating': 'BBB-', 'name': 'State Street', 'sector': 'Financials'},
    {'ticker': 'BK', 'rating': 'BBB-', 'name': 'Bank of NY Mellon', 'sector': 'Financials'},
    {'ticker': 'CMA', 'rating': 'BBB-', 'name': 'Comerica', 'sector': 'Financials'},
    {'ticker': 'ZION', 'rating': 'BBB-', 'name': 'Zions Bancorp', 'sector': 'Financials'},
    {'ticker': 'FRC', 'rating': 'BBB-', 'name': 'First Republic Bank', 'sector': 'Financials'},
    {'ticker': 'SBNY', 'rating': 'BBB-', 'name': 'Signature Bank', 'sector': 'Financials'},
    {'ticker': 'WAL', 'rating': 'BBB-', 'name': 'Western Alliance', 'sector': 'Financials'},
    {'ticker': 'PACW', 'rating': 'BBB-', 'name': 'PacWest Bancorp', 'sector': 'Financials'},
    {'ticker': 'KMI', 'rating': 'BBB-', 'name': 'Kinder Morgan', 'sector': 'Energy'},
    {'ticker': 'WMB', 'rating': 'BBB-', 'name': 'Williams Companies', 'sector': 'Energy'},
    {'ticker': 'OKE', 'rating': 'BBB-', 'name': 'ONEOK', 'sector': 'Energy'},
    {'ticker': 'TRGP', 'rating': 'BBB-', 'name': 'Targa Resources', 'sector': 'Energy'},
    {'ticker': 'ET', 'rating': 'BBB-', 'name': 'Energy Transfer', 'sector': 'Energy'},
    {'ticker': 'EPD', 'rating': 'BBB-', 'name': 'Enterprise Products', 'sector': 'Energy'},
    {'ticker': 'MPC', 'rating': 'BBB-', 'name': 'Marathon Petroleum', 'sector': 'Energy'},
    {'ticker': 'VLO', 'rating': 'BBB-', 'name': 'Valero Energy', 'sector': 'Energy'},
    {'ticker': 'PSX', 'rating': 'BBB-', 'name': 'Phillips 66', 'sector': 'Energy'},
    {'ticker': 'HES', 'rating': 'BBB-', 'name': 'Hess Corp', 'sector': 'Energy'},
    
    # ================================================================
    # BB+ to BB- (~80 companies - High Yield)
    # ================================================================
    {'ticker': 'UAL', 'rating': 'BB+', 'name': 'United Airlines', 'sector': 'Industrials'},
    {'ticker': 'RCL', 'rating': 'BB+', 'name': 'Royal Caribbean', 'sector': 'Consumer Discretionary'},
    {'ticker': 'NCLH', 'rating': 'BB+', 'name': 'Norwegian Cruise', 'sector': 'Consumer Discretionary'},
    {'ticker': 'CCL', 'rating': 'BB', 'name': 'Carnival', 'sector': 'Consumer Discretionary'},
    {'ticker': 'AAL', 'rating': 'BB-', 'name': 'American Airlines', 'sector': 'Industrials'},
    {'ticker': 'SAVE', 'rating': 'BB-', 'name': 'Spirit Airlines', 'sector': 'Industrials'},
    {'ticker': 'ALK', 'rating': 'BB', 'name': 'Alaska Air', 'sector': 'Industrials'},
    {'ticker': 'JBLU', 'rating': 'BB-', 'name': 'JetBlue Airways', 'sector': 'Industrials'},
    {'ticker': 'HA', 'rating': 'BB-', 'name': 'Hawaiian Holdings', 'sector': 'Industrials'},
    {'ticker': 'DISH', 'rating': 'BB-', 'name': 'Dish Network', 'sector': 'Communication'},
    {'ticker': 'LUMN', 'rating': 'BB-', 'name': 'Lumen Technologies', 'sector': 'Communication'},
    {'ticker': 'PARA', 'rating': 'BB', 'name': 'Paramount Global', 'sector': 'Communication'},
    {'ticker': 'WBD', 'rating': 'BB+', 'name': 'Warner Bros Discovery', 'sector': 'Communication'},
    {'ticker': 'FOX', 'rating': 'BB+', 'name': 'Fox Corp', 'sector': 'Communication'},
    {'ticker': 'FOXA', 'rating': 'BB+', 'name': 'Fox Corp Class A', 'sector': 'Communication'},
    {'ticker': 'LYV', 'rating': 'BB+', 'name': 'Live Nation', 'sector': 'Communication'},
    {'ticker': 'CHTR', 'rating': 'BB+', 'name': 'Charter Communications', 'sector': 'Communication'},
    {'ticker': 'LBRDK', 'rating': 'BB', 'name': 'Liberty Broadband', 'sector': 'Communication'},
    {'ticker': 'SIRI', 'rating': 'BB', 'name': 'Sirius XM', 'sector': 'Communication'},
    {'ticker': 'PK', 'rating': 'BB', 'name': 'Park Hotels', 'sector': 'Real Estate'},
    {'ticker': 'RHP', 'rating': 'BB', 'name': 'Ryman Hospitality', 'sector': 'Real Estate'},
    {'ticker': 'HST', 'rating': 'BB', 'name': 'Host Hotels', 'sector': 'Real Estate'},
    {'ticker': 'SHO', 'rating': 'BB-', 'name': 'Sunstone Hotel', 'sector': 'Real Estate'},
    {'ticker': 'RLJ', 'rating': 'BB-', 'name': 'RLJ Lodging', 'sector': 'Real Estate'},
    {'ticker': 'XRX', 'rating': 'BB+', 'name': 'Xerox', 'sector': 'Technology'},
    {'ticker': 'LSCC', 'rating': 'BB', 'name': 'Lattice Semi', 'sector': 'Technology'},
    {'ticker': 'WOLF', 'rating': 'BB-', 'name': 'Wolfspeed', 'sector': 'Technology'},
    {'ticker': 'HWM', 'rating': 'BB+', 'name': 'Howmet Aerospace', 'sector': 'Industrials'},
    {'ticker': 'TDG', 'rating': 'BB', 'name': 'TransDigm', 'sector': 'Industrials'},
    {'ticker': 'SPR', 'rating': 'BB', 'name': 'Spirit AeroSystems', 'sector': 'Industrials'},
    {'ticker': 'TXT', 'rating': 'BB+', 'name': 'Textron', 'sector': 'Industrials'},
    {'ticker': 'OSK', 'rating': 'BB+', 'name': 'Oshkosh', 'sector': 'Industrials'},
    {'ticker': 'BWA', 'rating': 'BB+', 'name': 'BorgWarner', 'sector': 'Consumer Discretionary'},
    {'ticker': 'APTV', 'rating': 'BB+', 'name': 'Aptiv', 'sector': 'Consumer Discretionary'},
    {'ticker': 'LEA', 'rating': 'BB+', 'name': 'Lear Corp', 'sector': 'Consumer Discretionary'},
    {'ticker': 'MGA', 'rating': 'BB+', 'name': 'Magna International', 'sector': 'Consumer Discretionary'},
    {'ticker': 'VC', 'rating': 'BB', 'name': 'Visteon', 'sector': 'Consumer Discretionary'},
    {'ticker': 'ALV', 'rating': 'BB', 'name': 'Autoliv', 'sector': 'Consumer Discretionary'},
    {'ticker': 'MOD', 'rating': 'BB', 'name': 'Modine Manufacturing', 'sector': 'Consumer Discretionary'},
    {'ticker': 'GT', 'rating': 'BB', 'name': 'Goodyear', 'sector': 'Consumer Discretionary'},
    {'ticker': 'CTB', 'rating': 'BB-', 'name': 'Cooper Tire', 'sector': 'Consumer Discretionary'},
    {'ticker': 'GPS', 'rating': 'BB', 'name': 'Gap Inc', 'sector': 'Consumer Discretionary'},
    {'ticker': 'KSS', 'rating': 'BB-', 'name': 'Kohls', 'sector': 'Consumer Discretionary'},
    {'ticker': 'M', 'rating': 'BB', 'name': 'Macys', 'sector': 'Consumer Discretionary'},
    {'ticker': 'JWN', 'rating': 'BB', 'name': 'Nordstrom', 'sector': 'Consumer Discretionary'},
    {'ticker': 'DDS', 'rating': 'BB', 'name': 'Dillards', 'sector': 'Consumer Discretionary'},
    {'ticker': 'URBN', 'rating': 'BB', 'name': 'Urban Outfitters', 'sector': 'Consumer Discretionary'},
    {'ticker': 'ANF', 'rating': 'BB', 'name': 'Abercrombie & Fitch', 'sector': 'Consumer Discretionary'},
    {'ticker': 'RL', 'rating': 'BB+', 'name': 'Ralph Lauren', 'sector': 'Consumer Discretionary'},
    {'ticker': 'PVH', 'rating': 'BB+', 'name': 'PVH Corp', 'sector': 'Consumer Discretionary'},
    {'ticker': 'TPR', 'rating': 'BB+', 'name': 'Tapestry', 'sector': 'Consumer Discretionary'},
    {'ticker': 'CPRI', 'rating': 'BB', 'name': 'Capri Holdings', 'sector': 'Consumer Discretionary'},
    {'ticker': 'VFC', 'rating': 'BB+', 'name': 'VF Corp', 'sector': 'Consumer Discretionary'},
    {'ticker': 'HBI', 'rating': 'BB', 'name': 'Hanesbrands', 'sector': 'Consumer Discretionary'},
    {'ticker': 'SKX', 'rating': 'BB+', 'name': 'Skechers', 'sector': 'Consumer Discretionary'},
    {'ticker': 'CROX', 'rating': 'BB', 'name': 'Crocs', 'sector': 'Consumer Discretionary'},
    {'ticker': 'FL', 'rating': 'BB', 'name': 'Foot Locker', 'sector': 'Consumer Discretionary'},
    {'ticker': 'DKS', 'rating': 'BB+', 'name': 'Dicks Sporting', 'sector': 'Consumer Discretionary'},
    {'ticker': 'ULTA', 'rating': 'BB+', 'name': 'Ulta Beauty', 'sector': 'Consumer Discretionary'},
    {'ticker': 'FIVE', 'rating': 'BB', 'name': 'Five Below', 'sector': 'Consumer Discretionary'},
    {'ticker': 'OLLI', 'rating': 'BB', 'name': 'Ollies Bargain', 'sector': 'Consumer Discretionary'},
    {'ticker': 'BIG', 'rating': 'BB-', 'name': 'Big Lots', 'sector': 'Consumer Discretionary'},
    
    # ================================================================
    # B+ to B- (~50 companies)
    # ================================================================
    {'ticker': 'GME', 'rating': 'B', 'name': 'GameStop', 'sector': 'Consumer Discretionary'},
    {'ticker': 'BBBY', 'rating': 'B-', 'name': 'Bed Bath Beyond', 'sector': 'Consumer Discretionary'},
    {'ticker': 'PRTY', 'rating': 'B', 'name': 'Party City', 'sector': 'Consumer Discretionary'},
    {'ticker': 'EXPR', 'rating': 'B-', 'name': 'Express Inc', 'sector': 'Consumer Discretionary'},
    {'ticker': 'TLRY', 'rating': 'B', 'name': 'Tilray', 'sector': 'Healthcare'},
    {'ticker': 'CGC', 'rating': 'B-', 'name': 'Canopy Growth', 'sector': 'Healthcare'},
    {'ticker': 'ACB', 'rating': 'B-', 'name': 'Aurora Cannabis', 'sector': 'Healthcare'},
    {'ticker': 'CRON', 'rating': 'B-', 'name': 'Cronos Group', 'sector': 'Healthcare'},
    {'ticker': 'SNDL', 'rating': 'B-', 'name': 'Sundial Growers', 'sector': 'Healthcare'},
    {'ticker': 'RIG', 'rating': 'B', 'name': 'Transocean', 'sector': 'Energy'},
    {'ticker': 'VAL', 'rating': 'B', 'name': 'Valaris', 'sector': 'Energy'},
    {'ticker': 'NE', 'rating': 'B', 'name': 'Noble Corp', 'sector': 'Energy'},
    {'ticker': 'HP', 'rating': 'B+', 'name': 'Helmerich & Payne', 'sector': 'Energy'},
    {'ticker': 'NBR', 'rating': 'B', 'name': 'Nabors Industries', 'sector': 'Energy'},
    {'ticker': 'PTEN', 'rating': 'B+', 'name': 'Patterson-UTI', 'sector': 'Energy'},
    {'ticker': 'SM', 'rating': 'B+', 'name': 'SM Energy', 'sector': 'Energy'},
    {'ticker': 'AR', 'rating': 'B+', 'name': 'Antero Resources', 'sector': 'Energy'},
    {'ticker': 'RRC', 'rating': 'B+', 'name': 'Range Resources', 'sector': 'Energy'},
    {'ticker': 'SWN', 'rating': 'B+', 'name': 'Southwestern Energy', 'sector': 'Energy'},
    {'ticker': 'CNX', 'rating': 'B+', 'name': 'CNX Resources', 'sector': 'Energy'},
    {'ticker': 'EQT', 'rating': 'B+', 'name': 'EQT Corp', 'sector': 'Energy'},
    {'ticker': 'CTRA', 'rating': 'B+', 'name': 'Coterra Energy', 'sector': 'Energy'},
    {'ticker': 'GPRO', 'rating': 'B', 'name': 'GoPro', 'sector': 'Technology'},
    {'ticker': 'SONO', 'rating': 'B', 'name': 'Sonos', 'sector': 'Technology'},
    {'ticker': 'IRBT', 'rating': 'B', 'name': 'iRobot', 'sector': 'Technology'},
    {'ticker': 'HEAR', 'rating': 'B-', 'name': 'Turtle Beach', 'sector': 'Technology'},
    {'ticker': 'KOSS', 'rating': 'B-', 'name': 'Koss Corp', 'sector': 'Technology'},
    {'ticker': 'VUZI', 'rating': 'B-', 'name': 'Vuzix', 'sector': 'Technology'},
    {'ticker': 'BBAI', 'rating': 'B-', 'name': 'BigBear.ai', 'sector': 'Technology'},
    {'ticker': 'PLTR', 'rating': 'B+', 'name': 'Palantir', 'sector': 'Technology'},
    {'ticker': 'SNOW', 'rating': 'B+', 'name': 'Snowflake', 'sector': 'Technology'},
    {'ticker': 'DDOG', 'rating': 'B+', 'name': 'Datadog', 'sector': 'Technology'},
    {'ticker': 'ZS', 'rating': 'B+', 'name': 'Zscaler', 'sector': 'Technology'},
    {'ticker': 'CRWD', 'rating': 'B+', 'name': 'CrowdStrike', 'sector': 'Technology'},
    {'ticker': 'OKTA', 'rating': 'B', 'name': 'Okta', 'sector': 'Technology'},
    {'ticker': 'MDB', 'rating': 'B', 'name': 'MongoDB', 'sector': 'Technology'},
    {'ticker': 'NET', 'rating': 'B', 'name': 'Cloudflare', 'sector': 'Technology'},
    {'ticker': 'DOCN', 'rating': 'B', 'name': 'DigitalOcean', 'sector': 'Technology'},
    {'ticker': 'ESTC', 'rating': 'B', 'name': 'Elastic NV', 'sector': 'Technology'},
    {'ticker': 'CFLT', 'rating': 'B', 'name': 'Confluent', 'sector': 'Technology'},
    {'ticker': 'PD', 'rating': 'B', 'name': 'PagerDuty', 'sector': 'Technology'},
    {'ticker': 'SUMO', 'rating': 'B-', 'name': 'Sumo Logic', 'sector': 'Technology'},
    {'ticker': 'NEWR', 'rating': 'B', 'name': 'New Relic', 'sector': 'Technology'},
    {'ticker': 'DT', 'rating': 'B', 'name': 'Dynatrace', 'sector': 'Technology'},
    {'ticker': 'SPLK', 'rating': 'B+', 'name': 'Splunk', 'sector': 'Technology'},
    
    # ================================================================
    # CCC+ to CCC- (~30 companies)
    # ================================================================
    {'ticker': 'AMC', 'rating': 'CCC+', 'name': 'AMC Entertainment', 'sector': 'Communication'},
    {'ticker': 'CNK', 'rating': 'CCC+', 'name': 'Cinemark', 'sector': 'Communication'},
    {'ticker': 'IMAX', 'rating': 'CCC+', 'name': 'IMAX Corp', 'sector': 'Communication'},
    {'ticker': 'LGF-A', 'rating': 'CCC', 'name': 'Lions Gate', 'sector': 'Communication'},
    {'ticker': 'WWE', 'rating': 'CCC+', 'name': 'World Wrestling', 'sector': 'Communication'},
    {'ticker': 'EDR', 'rating': 'CCC', 'name': 'Endeavor Group', 'sector': 'Communication'},
    {'ticker': 'HTZ', 'rating': 'CCC', 'name': 'Hertz', 'sector': 'Industrials'},
    {'ticker': 'CAR', 'rating': 'CCC+', 'name': 'Avis Budget', 'sector': 'Industrials'},
    {'ticker': 'R', 'rating': 'CCC+', 'name': 'Ryder System', 'sector': 'Industrials'},
    {'ticker': 'URI', 'rating': 'CCC+', 'name': 'United Rentals', 'sector': 'Industrials'},
    {'ticker': 'SNDR', 'rating': 'CCC', 'name': 'Schneider National', 'sector': 'Industrials'},
    {'ticker': 'KNX', 'rating': 'CCC', 'name': 'Knight-Swift', 'sector': 'Industrials'},
    {'ticker': 'WERN', 'rating': 'CCC', 'name': 'Werner Enterprises', 'sector': 'Industrials'},
    {'ticker': 'JBHT', 'rating': 'CCC+', 'name': 'JB Hunt', 'sector': 'Industrials'},
    {'ticker': 'XPO', 'rating': 'CCC+', 'name': 'XPO Logistics', 'sector': 'Industrials'},
    {'ticker': 'CHRW', 'rating': 'CCC', 'name': 'CH Robinson', 'sector': 'Industrials'},
    {'ticker': 'EXPD', 'rating': 'CCC', 'name': 'Expeditors Intl', 'sector': 'Industrials'},
    {'ticker': 'RVLV', 'rating': 'CCC', 'name': 'Revolve Group', 'sector': 'Consumer Discretionary'},
    {'ticker': 'FTCH', 'rating': 'CCC-', 'name': 'Farfetch', 'sector': 'Consumer Discretionary'},
    {'ticker': 'REAL', 'rating': 'CCC-', 'name': 'RealReal', 'sector': 'Consumer Discretionary'},
    {'ticker': 'POSH', 'rating': 'CCC', 'name': 'Poshmark', 'sector': 'Consumer Discretionary'},
    {'ticker': 'ETSY', 'rating': 'CCC+', 'name': 'Etsy', 'sector': 'Consumer Discretionary'},
    {'ticker': 'W', 'rating': 'CCC+', 'name': 'Wayfair', 'sector': 'Consumer Discretionary'},
    {'ticker': 'PTON', 'rating': 'CCC', 'name': 'Peloton', 'sector': 'Consumer Discretionary'},
    {'ticker': 'BIRD', 'rating': 'CCC-', 'name': 'Allbirds', 'sector': 'Consumer Discretionary'},
    {'ticker': 'SFIX', 'rating': 'CCC', 'name': 'Stitch Fix', 'sector': 'Consumer Discretionary'},
    {'ticker': 'RENT', 'rating': 'CCC-', 'name': 'Rent the Runway', 'sector': 'Consumer Discretionary'},
    {'ticker': 'CHWY', 'rating': 'CCC+', 'name': 'Chewy', 'sector': 'Consumer Discretionary'},
    {'ticker': 'CVNA', 'rating': 'CCC', 'name': 'Carvana', 'sector': 'Consumer Discretionary'},
    {'ticker': 'VRM', 'rating': 'CCC-', 'name': 'Vroom', 'sector': 'Consumer Discretionary'},
    {'ticker': 'OPEN', 'rating': 'CCC', 'name': 'Opendoor', 'sector': 'Real Estate'},
    {'ticker': 'RDFN', 'rating': 'CCC', 'name': 'Redfin', 'sector': 'Real Estate'},
    {'ticker': 'COMP', 'rating': 'CCC', 'name': 'Compass Inc', 'sector': 'Real Estate'},
    
    # ================================================================
    # D (Default/Distressed - ~10 companies - historical examples)
    # ================================================================
    # Note: These are historical examples; actual D-rated companies change frequently
    {'ticker': 'BYON', 'rating': 'D', 'name': 'Beyond Inc', 'sector': 'Consumer Discretionary'},
    {'ticker': 'BBBYQ', 'rating': 'D', 'name': 'Bed Bath Beyond (Bankrupt)', 'sector': 'Consumer Discretionary'},
    {'ticker': 'RVPHQ', 'rating': 'D', 'name': 'Revlon (Bankrupt)', 'sector': 'Consumer Staples'},
]


# Summary statistics
def get_rating_distribution():
    """Get distribution of ratings in training data"""
    from collections import Counter
    
    rating_map = {
        'AAA': 0, 'AA+': 1, 'AA': 1, 'AA-': 1,
        'A+': 2, 'A': 2, 'A-': 2,
        'BBB+': 3, 'BBB': 3, 'BBB-': 3,
        'BB+': 4, 'BB': 4, 'BB-': 4,
        'B+': 5, 'B': 5, 'B-': 5,
        'CCC+': 6, 'CCC': 6, 'CCC-': 6,
        'D': 7
    }
    
    rating_names = ['AAA', 'AA', 'A', 'BBB', 'BB', 'B', 'CCC', 'D']
    
    nums = [rating_map.get(c['rating'], 3) for c in LARGE_TRAINING_COMPANIES]
    counter = Counter(nums)
    
    print(f"Total companies: {len(LARGE_TRAINING_COMPANIES)}")
    print("\nRating Distribution:")
    for i, name in enumerate(rating_names):
        count = counter.get(i, 0)
        pct = count / len(LARGE_TRAINING_COMPANIES) * 100
        bar = "#" * int(pct / 2)
        print(f"  {name:>4}: {count:>4} ({pct:>5.1f}%) {bar}")


if __name__ == "__main__":
    get_rating_distribution()